// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schedules.proto

package com.pq.gtfs.models.Schedules;

public final class Schedules {
  private Schedules() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehicleDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Schedules.proto\022\020transit_realtime\"\314\"\n\013" +
      "FeedMessage\0228\n\006header\030\001 \002(\0132(.transit_re" +
      "altime.FeedMessage.FeedHeader\0228\n\006entity\030" +
      "\002 \002(\0132(.transit_realtime.FeedMessage.Fee" +
      "dEntity\032\323\001\n\nFeedHeader\022\035\n\025gtfs_realtime_" +
      "version\030\001 \002(\t\022]\n\016incrementality\030\002 \001(\01627." +
      "transit_realtime.FeedMessage.FeedHeader." +
      "Incrementality:\014FULL_DATASET\022\021\n\ttimestam" +
      "p\030\003 \001(\004\"4\n\016Incrementality\022\020\n\014FULL_DATASE" +
      "T\020\000\022\020\n\014DIFFERENTIAL\020\001\032\311\014\n\nFeedEntity\022\n\n\002" +
      "id\030\001 \002(\t\022\031\n\nis_deleted\030\002 \001(\010:\005false\022=\n\013t" +
      "rip_update\030\003 \001(\0132(.transit_realtime.Feed" +
      "Message.TripUpdate\022>\n\007vehicle\030\004 \001(\0132-.tr" +
      "ansit_realtime.FeedMessage.VehiclePositi" +
      "on\022=\n\005alert\030\005 \001(\0132..transit_realtime.Fee" +
      "dMessage.FeedEntity.Alert\032\325\n\n\005Alert\022O\n\ra" +
      "ctive_period\030\001 \001(\01328.transit_realtime.Fe" +
      "edMessage.FeedEntity.Alert.TimeRange\022V\n\017" +
      "informed_entity\030\002 \001(\0132=.transit_realtime" +
      ".FeedMessage.FeedEntity.Alert.EntitySele" +
      "ctor\022R\n\005cause\030\003 \001(\01624.transit_realtime.F" +
      "eedMessage.FeedEntity.Alert.Cause:\rUNKNO" +
      "WN_CAUSE\022U\n\006effect\030\004 \001(\01625.transit_realt" +
      "ime.FeedMessage.FeedEntity.Alert.Effect:" +
      "\016UNKNOWN_EFFECT\022L\n\003url\030\005 \001(\0132?.transit_r" +
      "ealtime.FeedMessage.FeedEntity.Alert.Tra" +
      "nslatedString\022T\n\013header_text\030\006 \001(\0132?.tra" +
      "nsit_realtime.FeedMessage.FeedEntity.Ale" +
      "rt.TranslatedString\022Y\n\020description_text\030" +
      "\007 \001(\0132?.transit_realtime.FeedMessage.Fee" +
      "dEntity.Alert.TranslatedString\032\'\n\tTimeRa" +
      "nge\022\r\n\005start\030\001 \001(\004\022\013\n\003end\030\002 \001(\004\032\226\001\n\016Enti" +
      "tySelector\022\021\n\tagency_id\030\001 \001(\t\022\020\n\010route_i" +
      "d\030\002 \001(\t\022\022\n\nroute_type\030\003 \001(\005\022:\n\004trip\030\004 \001(" +
      "\0132,.transit_realtime.FeedMessage.TripDes" +
      "criptor\022\017\n\007stop_id\030\005 \001(\t\032\243\001\n\020TranslatedS" +
      "tring\022`\n\013translation\030\001 \001(\0132K.transit_rea" +
      "ltime.FeedMessage.FeedEntity.Alert.Trans" +
      "latedString.Translation\032-\n\013Translation\022\014" +
      "\n\004text\030\001 \002(\t\022\020\n\010language\030\002 \001(\t\"\330\001\n\005Cause" +
      "\022\021\n\rUNKNOWN_CAUSE\020\001\022\017\n\013OTHER_CAUSE\020\002\022\025\n\021" +
      "TECHNICAL_PROBLEM\020\003\022\n\n\006STRIKE\020\004\022\021\n\rDEMON" +
      "STRATION\020\005\022\014\n\010ACCIDENT\020\006\022\013\n\007HOLIDAY\020\007\022\013\n" +
      "\007WEATHER\020\010\022\017\n\013MAINTENANCE\020\t\022\020\n\014CONSTRUCT" +
      "ION\020\n\022\023\n\017POLICE_ACTIVITY\020\013\022\025\n\021MEDICAL_EM" +
      "ERGENCY\020\014\"\265\001\n\006Effect\022\016\n\nNO_SERVICE\020\001\022\023\n\017" +
      "REDUCED_SERVICE\020\002\022\026\n\022SIGNIFICANT_DELAYS\020" +
      "\003\022\n\n\006DETOUR\020\004\022\026\n\022ADDITIONAL_SERVICE\020\005\022\024\n" +
      "\020MODIFIED_SERVICE\020\006\022\020\n\014OTHER_EFFECT\020\007\022\022\n" +
      "\016UNKNOWN_EFFECT\020\010\022\016\n\nSTOP_MOVED\020\t\032\340\003\n\016Tr" +
      "ipDescriptor\022\017\n\007trip_id\030\001 \002(\t\022\027\n\017trip_sh" +
      "ort_name\030\002 \001(\t\022\020\n\010route_id\030\003 \002(\t\022\030\n\020rout" +
      "e_short_name\030\004 \001(\t\022\027\n\017route_long_name\030\005 " +
      "\001(\t\022\017\n\007line_id\030\006 \002(\t\022\027\n\017line_short_name\030" +
      "\007 \001(\t\022\026\n\016line_long_name\030\010 \001(\t\022\025\n\rextra_t" +
      "rip_id\030\t \001(\t\022\024\n\014direction_id\030\n \001(\r\022\022\n\nst" +
      "art_time\030\013 \001(\t\022\022\n\nstart_date\030\014 \001(\t\022\025\n\rpl" +
      "atform_code\030\r \001(\t\022`\n\025schedule_relationsh" +
      "ip\030\016 \001(\0162A.transit_realtime.FeedMessage." +
      "TripDescriptor.ScheduleRelationship\"O\n\024S" +
      "cheduleRelationship\022\r\n\tSCHEDULED\020\000\022\t\n\005AD" +
      "DED\020\001\022\017\n\013UNSCHEDULED\020\002\022\014\n\010CANCELED\020\003\032k\n\021" +
      "VehicleDescriptor\022\n\n\002id\030\001 \001(\t\022\r\n\005label\030\002" +
      " \001(\t\022\025\n\rlicense_plate\030\003 \001(\t\022\022\n\nwheelchai" +
      "r\030\004 \002(\010\022\020\n\010bicycles\030\005 \002(\010\032\300\006\n\nTripUpdate" +
      "\022\031\n\021operation_plan_id\030\001 \001(\t\022\021\n\tagency_id" +
      "\030\002 \001(\t\022:\n\004trip\030\003 \002(\0132,.transit_realtime." +
      "FeedMessage.TripDescriptor\022@\n\007vehicle\030\004 " +
      "\001(\0132/.transit_realtime.FeedMessage.Vehic" +
      "leDescriptor\022Q\n\020stop_time_update\030\005 \002(\01327" +
      ".transit_realtime.FeedMessage.TripUpdate" +
      ".StopTimeUpdate\022\025\n\rplatform_code\030\006 \001(\t\022\021" +
      "\n\ttimestamp\030\007 \001(\004\022\r\n\005delay\030\010 \001(\005\032\371\003\n\016Sto" +
      "pTimeUpdate\022\025\n\rstop_sequence\030\001 \001(\r\022\017\n\007st" +
      "op_id\030\002 \001(\t\022\021\n\tstop_name\030\003 \001(\t\022V\n\007arriva" +
      "l\030\004 \001(\0132E.transit_realtime.FeedMessage.T" +
      "ripUpdate.StopTimeUpdate.StopTimeEvent\022X" +
      "\n\tdeparture\030\005 \001(\0132E.transit_realtime.Fee" +
      "dMessage.TripUpdate.StopTimeUpdate.StopT" +
      "imeEvent\022v\n\025schedule_relationship\030\006 \001(\0162" +
      "L.transit_realtime.FeedMessage.TripUpdat" +
      "e.StopTimeUpdate.ScheduleRelationship:\tS" +
      "CHEDULED\032A\n\rStopTimeEvent\022\r\n\005delay\030\001 \001(\005" +
      "\022\014\n\004time\030\002 \001(\003\022\023\n\013uncertainty\030\003 \001(\005\"?\n\024S" +
      "cheduleRelationship\022\r\n\tSCHEDULED\020\000\022\013\n\007SK" +
      "IPPED\020\001\022\013\n\007NO_DATA\020\002\032\223\010\n\017VehiclePosition" +
      "\022:\n\004trip\030\001 \001(\0132,.transit_realtime.FeedMe" +
      "ssage.TripDescriptor\022@\n\007vehicle\030\002 \001(\0132/." +
      "transit_realtime.FeedMessage.VehicleDesc" +
      "riptor\022H\n\010position\030\003 \001(\01326.transit_realt" +
      "ime.FeedMessage.VehiclePosition.Position" +
      "\022\035\n\025current_stop_sequence\030\004 \001(\r\022\017\n\007stop_" +
      "id\030\005 \001(\t\022f\n\016current_status\030\006 \001(\0162?.trans" +
      "it_realtime.FeedMessage.VehiclePosition." +
      "VehicleStopStatus:\rIN_TRANSIT_TO\022\021\n\ttime" +
      "stamp\030\007 \001(\004\022W\n\020congestion_level\030\010 \001(\0162=." +
      "transit_realtime.FeedMessage.VehiclePosi" +
      "tion.CongestionLevel\022W\n\020occupancy_status" +
      "\030\t \001(\0162=.transit_realtime.FeedMessage.Ve" +
      "hiclePosition.OccupancyStatus\032a\n\010Positio" +
      "n\022\020\n\010latitude\030\001 \002(\002\022\021\n\tlongitude\030\002 \002(\002\022\017" +
      "\n\007bearing\030\003 \001(\002\022\020\n\010odometer\030\004 \001(\001\022\r\n\005spe" +
      "ed\030\005 \001(\002\"G\n\021VehicleStopStatus\022\017\n\013INCOMIN" +
      "G_AT\020\000\022\016\n\nSTOPPED_AT\020\001\022\021\n\rIN_TRANSIT_TO\020" +
      "\002\"}\n\017CongestionLevel\022\034\n\030UNKNOWN_CONGESTI" +
      "ON_LEVEL\020\000\022\024\n\020RUNNING_SMOOTHLY\020\001\022\017\n\013STOP" +
      "_AND_GO\020\002\022\016\n\nCONGESTION\020\003\022\025\n\021SEVERE_CONG" +
      "ESTION\020\004\"\257\001\n\017OccupancyStatus\022\t\n\005EMPTY\020\000\022" +
      "\030\n\024MANY_SEATS_AVAILABLE\020\001\022\027\n\023FEW_SEATS_A" +
      "VAILABLE\020\002\022\026\n\022STANDING_ROOM_ONLY\020\003\022\036\n\032CR" +
      "USHED_STANDING_ROOM_ONLY\020\004\022\010\n\004FULL\020\005\022\034\n\030" +
      "NOT_ACCEPTING_PASSENGERS\020\006B \n\034com.pq.gtf" +
      "s.models.SchedulesP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transit_realtime_FeedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_FeedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_descriptor,
        new java.lang.String[] { "Header", "Entity", });
    internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor,
        new java.lang.String[] { "GtfsRealtimeVersion", "Incrementality", "Timestamp", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor,
        new java.lang.String[] { "Id", "IsDeleted", "TripUpdate", "Vehicle", "Alert", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor,
        new java.lang.String[] { "ActivePeriod", "InformedEntity", "Cause", "Effect", "Url", "HeaderText", "DescriptionText", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor,
        new java.lang.String[] { "AgencyId", "RouteId", "RouteType", "Trip", "StopId", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor,
        new java.lang.String[] { "Translation", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor,
        new java.lang.String[] { "Text", "Language", });
    internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_TripDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor,
        new java.lang.String[] { "TripId", "TripShortName", "RouteId", "RouteShortName", "RouteLongName", "LineId", "LineShortName", "LineLongName", "ExtraTripId", "DirectionId", "StartTime", "StartDate", "PlatformCode", "ScheduleRelationship", });
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(3);
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor,
        new java.lang.String[] { "Id", "Label", "LicensePlate", "Wheelchair", "Bicycles", });
    internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(4);
    internal_static_transit_realtime_FeedMessage_TripUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor,
        new java.lang.String[] { "OperationPlanId", "AgencyId", "Trip", "Vehicle", "StopTimeUpdate", "PlatformCode", "Timestamp", "Delay", });
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor =
      internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor,
        new java.lang.String[] { "StopSequence", "StopId", "StopName", "Arrival", "Departure", "ScheduleRelationship", });
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor =
      internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor,
        new java.lang.String[] { "Delay", "Time", "Uncertainty", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(5);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor,
        new java.lang.String[] { "Trip", "Vehicle", "Position", "CurrentStopSequence", "StopId", "CurrentStatus", "Timestamp", "CongestionLevel", "OccupancyStatus", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor =
      internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Bearing", "Odometer", "Speed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
