// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleEvents.proto

package com.pq.gtfs.models.VehicleEvents;

public final class VehicleEvents {
  private VehicleEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehicleDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_PassengerCounting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_PassengerCounting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_Consumption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_Consumption_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023VehicleEvents.proto\022\020transit_realtime\032" +
      "\037google/protobuf/timestamp.proto\"\356(\n\013Fee" +
      "dMessage\0228\n\006header\030\001 \002(\0132(.transit_realt" +
      "ime.FeedMessage.FeedHeader\0228\n\006entity\030\002 \002" +
      "(\0132(.transit_realtime.FeedMessage.FeedEn" +
      "tity\032\357\001\n\nFeedHeader\022\035\n\025gtfs_realtime_ver" +
      "sion\030\001 \002(\t\022]\n\016incrementality\030\002 \001(\01627.tra" +
      "nsit_realtime.FeedMessage.FeedHeader.Inc" +
      "rementality:\014FULL_DATASET\022-\n\ttimestamp\030\003" +
      " \001(\0132\032.google.protobuf.Timestamp\"4\n\016Incr" +
      "ementality\022\020\n\014FULL_DATASET\020\000\022\020\n\014DIFFEREN" +
      "TIAL\020\001\032\201\r\n\nFeedEntity\022\n\n\002id\030\001 \002(\t\022\031\n\nis_" +
      "deleted\030\002 \001(\010:\005false\022=\n\013trip_update\030\003 \001(" +
      "\0132(.transit_realtime.FeedMessage.TripUpd" +
      "ate\022>\n\007vehicle\030\004 \001(\0132-.transit_realtime." +
      "FeedMessage.VehiclePosition\022=\n\005alert\030\005 \001" +
      "(\0132..transit_realtime.FeedMessage.FeedEn" +
      "tity.Alert\032\215\013\n\005Alert\022O\n\ractive_period\030\001 " +
      "\001(\01328.transit_realtime.FeedMessage.FeedE" +
      "ntity.Alert.TimeRange\022V\n\017informed_entity" +
      "\030\002 \001(\0132=.transit_realtime.FeedMessage.Fe" +
      "edEntity.Alert.EntitySelector\022R\n\005cause\030\003" +
      " \001(\01624.transit_realtime.FeedMessage.Feed" +
      "Entity.Alert.Cause:\rUNKNOWN_CAUSE\022U\n\006eff" +
      "ect\030\004 \001(\01625.transit_realtime.FeedMessage" +
      ".FeedEntity.Alert.Effect:\016UNKNOWN_EFFECT" +
      "\022L\n\003url\030\005 \001(\0132?.transit_realtime.FeedMes" +
      "sage.FeedEntity.Alert.TranslatedString\022T" +
      "\n\013header_text\030\006 \001(\0132?.transit_realtime.F" +
      "eedMessage.FeedEntity.Alert.TranslatedSt" +
      "ring\022Y\n\020description_text\030\007 \001(\0132?.transit" +
      "_realtime.FeedMessage.FeedEntity.Alert.T" +
      "ranslatedString\032_\n\tTimeRange\022)\n\005start\030\001 " +
      "\001(\0132\032.google.protobuf.Timestamp\022\'\n\003end\030\002" +
      " \001(\0132\032.google.protobuf.Timestamp\032\226\001\n\016Ent" +
      "itySelector\022\021\n\tagency_id\030\001 \001(\t\022\020\n\010route_" +
      "id\030\002 \001(\t\022\022\n\nroute_type\030\003 \001(\005\022:\n\004trip\030\004 \001" +
      "(\0132,.transit_realtime.FeedMessage.TripDe" +
      "scriptor\022\017\n\007stop_id\030\005 \001(\t\032\243\001\n\020Translated" +
      "String\022`\n\013translation\030\001 \002(\0132K.transit_re" +
      "altime.FeedMessage.FeedEntity.Alert.Tran" +
      "slatedString.Translation\032-\n\013Translation\022" +
      "\014\n\004text\030\001 \002(\t\022\020\n\010language\030\002 \001(\t\"\330\001\n\005Caus" +
      "e\022\021\n\rUNKNOWN_CAUSE\020\001\022\017\n\013OTHER_CAUSE\020\002\022\025\n" +
      "\021TECHNICAL_PROBLEM\020\003\022\n\n\006STRIKE\020\004\022\021\n\rDEMO" +
      "NSTRATION\020\005\022\014\n\010ACCIDENT\020\006\022\013\n\007HOLIDAY\020\007\022\013" +
      "\n\007WEATHER\020\010\022\017\n\013MAINTENANCE\020\t\022\020\n\014CONSTRUC" +
      "TION\020\n\022\023\n\017POLICE_ACTIVITY\020\013\022\025\n\021MEDICAL_E" +
      "MERGENCY\020\014\"\265\001\n\006Effect\022\016\n\nNO_SERVICE\020\001\022\023\n" +
      "\017REDUCED_SERVICE\020\002\022\026\n\022SIGNIFICANT_DELAYS" +
      "\020\003\022\n\n\006DETOUR\020\004\022\026\n\022ADDITIONAL_SERVICE\020\005\022\024" +
      "\n\020MODIFIED_SERVICE\020\006\022\020\n\014OTHER_EFFECT\020\007\022\022" +
      "\n\016UNKNOWN_EFFECT\020\010\022\016\n\nSTOP_MOVED\020\t\032\365\002\n\016T" +
      "ripDescriptor\022\017\n\007trip_id\030\001 \001(\t\022\020\n\010route_" +
      "id\030\002 \001(\t\022\017\n\007line_id\030\003 \001(\t\022\025\n\rextra_trip_" +
      "id\030\004 \001(\t\022\023\n\013dead_run_id\030\005 \001(\t\022\022\n\nlayover" +
      "_id\030\006 \001(\t\022\024\n\014direction_id\030\007 \001(\r\022\022\n\nstart" +
      "_time\030\010 \001(\t\022\022\n\nstart_date\030\t \001(\t\022`\n\025sched" +
      "ule_relationship\030\n \001(\0162A.transit_realtim" +
      "e.FeedMessage.TripDescriptor.ScheduleRel" +
      "ationship\"O\n\024ScheduleRelationship\022\r\n\tSCH" +
      "EDULED\020\000\022\t\n\005ADDED\020\001\022\017\n\013UNSCHEDULED\020\002\022\014\n\010" +
      "CANCELED\020\003\032|\n\021VehicleDescriptor\022\n\n\002id\030\001 " +
      "\001(\t\022\020\n\010block_id\030\002 \001(\t\022\021\n\tdriver_id\030\003 \001(\t" +
      "\022\020\n\010shift_id\030\004 \001(\t\022\r\n\005label\030\005 \001(\t\022\025\n\rlic" +
      "ense_plate\030\006 \001(\t\032\204\006\n\nTripUpdate\022:\n\004trip\030" +
      "\001 \002(\0132,.transit_realtime.FeedMessage.Tri" +
      "pDescriptor\022@\n\007vehicle\030\002 \001(\0132/.transit_r" +
      "ealtime.FeedMessage.VehicleDescriptor\022Q\n" +
      "\020stop_time_update\030\003 \002(\01327.transit_realti" +
      "me.FeedMessage.TripUpdate.StopTimeUpdate" +
      "\022-\n\ttimestamp\030\004 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022\r\n\005delay\030\005 \001(\005\032\346\003\n\016StopTimeUpdat" +
      "e\022\025\n\rstop_sequence\030\001 \001(\r\022\017\n\007stop_id\030\002 \001(" +
      "\t\022V\n\007arrival\030\003 \001(\0132E.transit_realtime.Fe" +
      "edMessage.TripUpdate.StopTimeUpdate.Stop" +
      "TimeEvent\022X\n\tdeparture\030\004 \001(\0132E.transit_r" +
      "ealtime.FeedMessage.TripUpdate.StopTimeU" +
      "pdate.StopTimeEvent\022v\n\025schedule_relation" +
      "ship\030\005 \001(\0162L.transit_realtime.FeedMessag" +
      "e.TripUpdate.StopTimeUpdate.ScheduleRela" +
      "tionship:\tSCHEDULED\032A\n\rStopTimeEvent\022\r\n\005" +
      "delay\030\001 \001(\005\022\014\n\004time\030\002 \001(\003\022\023\n\013uncertainty" +
      "\030\003 \001(\005\"?\n\024ScheduleRelationship\022\r\n\tSCHEDU" +
      "LED\020\000\022\013\n\007SKIPPED\020\001\022\013\n\007NO_DATA\020\002\032\367\016\n\017Vehi" +
      "clePosition\022\031\n\021operation_plan_id\030\001 \002(\t\022\021" +
      "\n\tagency_id\030\002 \002(\t\022:\n\004trip\030\003 \001(\0132,.transi" +
      "t_realtime.FeedMessage.TripDescriptor\022@\n" +
      "\007vehicle\030\004 \001(\0132/.transit_realtime.FeedMe" +
      "ssage.VehicleDescriptor\022H\n\010position\030\005 \001(" +
      "\01326.transit_realtime.FeedMessage.Vehicle" +
      "Position.Position\022[\n\022passenger_counting\030" +
      "\006 \001(\0132?.transit_realtime.FeedMessage.Veh" +
      "iclePosition.PassengerCounting\022M\n\013eco_dr" +
      "iving\030\007 \001(\01328.transit_realtime.FeedMessa" +
      "ge.VehiclePosition.EcoDriving\022\035\n\025current" +
      "_stop_sequence\030\010 \001(\r\022\017\n\007stop_id\030\t \001(\t\022f\n" +
      "\016current_status\030\n \001(\0162?.transit_realtime" +
      ".FeedMessage.VehiclePosition.VehicleStop" +
      "Status:\rIN_TRANSIT_TO\022\021\n\ttimestamp\030\013 \001(\004" +
      "\022W\n\020congestion_level\030\014 \001(\0162=.transit_rea" +
      "ltime.FeedMessage.VehiclePosition.Conges" +
      "tionLevel\022W\n\020occupancy_status\030\r \001(\0162=.tr" +
      "ansit_realtime.FeedMessage.VehiclePositi" +
      "on.OccupancyStatus\032a\n\010Position\022\020\n\010latitu" +
      "de\030\001 \002(\001\022\021\n\tlongitude\030\002 \002(\001\022\017\n\007bearing\030\003" +
      " \001(\001\022\020\n\010odometer\030\004 \001(\001\022\r\n\005speed\030\005 \001(\001\032I\n" +
      "\021PassengerCounting\022\020\n\010class_id\030\001 \002(\t\022\020\n\010" +
      "incoming\030\002 \002(\005\022\020\n\010outgoing\030\003 \002(\005\032\274\004\n\nEco" +
      "Driving\022\020\n\010distance\030\001 \002(\005\022Y\n\013consumption" +
      "\030\002 \001(\0132D.transit_realtime.FeedMessage.Ve" +
      "hiclePosition.EcoDriving.Consumption\022\025\n\r" +
      "average_speed\030\003 \002(\002\022\034\n\024average_accelerat" +
      "ion\030\004 \002(\002\022\034\n\024sudden_accelerations\030\005 \002(\005\022" +
      "\034\n\024average_deceleration\030\006 \002(\002\022\034\n\024sudden_" +
      "decelerations\030\007 \002(\005\032\261\002\n\013Consumption\022g\n\004t" +
      "ype\030\001 \002(\0162Y.transit_realtime.FeedMessage" +
      ".VehiclePosition.EcoDriving.Consumption." +
      "PropulsionTechnology\022\r\n\005value\030\002 \002(\002\"\251\001\n\024" +
      "PropulsionTechnology\022\024\n\020UNKNOWN_or_empty" +
      "\020\000\022\014\n\010GASOLINE\020\001\022\n\n\006DIESEL\020\002\022\014\n\010LPG_AUTO" +
      "\020\003\022\013\n\007MIXTURE\020\004\022\r\n\tBIODIESEL\020\005\022\017\n\013ELECTR" +
      "ICITY\020\006\022\n\n\006HYBRID\020\007\022\017\n\013NATURAL_GAS\020\010\022\t\n\005" +
      "OTHER\020\t\"G\n\021VehicleStopStatus\022\017\n\013INCOMING" +
      "_AT\020\000\022\016\n\nSTOPPED_AT\020\001\022\021\n\rIN_TRANSIT_TO\020\002" +
      "\"}\n\017CongestionLevel\022\034\n\030UNKNOWN_CONGESTIO" +
      "N_LEVEL\020\000\022\024\n\020RUNNING_SMOOTHLY\020\001\022\017\n\013STOP_" +
      "AND_GO\020\002\022\016\n\nCONGESTION\020\003\022\025\n\021SEVERE_CONGE" +
      "STION\020\004\"\257\001\n\017OccupancyStatus\022\t\n\005EMPTY\020\000\022\030" +
      "\n\024MANY_SEATS_AVAILABLE\020\001\022\027\n\023FEW_SEATS_AV" +
      "AILABLE\020\002\022\026\n\022STANDING_ROOM_ONLY\020\003\022\036\n\032CRU" +
      "SHED_STANDING_ROOM_ONLY\020\004\022\010\n\004FULL\020\005\022\034\n\030N" +
      "OT_ACCEPTING_PASSENGERS\020\006B$\n com.pq.gtfs" +
      ".models.VehicleEventsP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_transit_realtime_FeedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_FeedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_descriptor,
        new java.lang.String[] { "Header", "Entity", });
    internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor,
        new java.lang.String[] { "GtfsRealtimeVersion", "Incrementality", "Timestamp", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor,
        new java.lang.String[] { "Id", "IsDeleted", "TripUpdate", "Vehicle", "Alert", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor,
        new java.lang.String[] { "ActivePeriod", "InformedEntity", "Cause", "Effect", "Url", "HeaderText", "DescriptionText", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor,
        new java.lang.String[] { "AgencyId", "RouteId", "RouteType", "Trip", "StopId", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor,
        new java.lang.String[] { "Translation", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor,
        new java.lang.String[] { "Text", "Language", });
    internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_TripDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor,
        new java.lang.String[] { "TripId", "RouteId", "LineId", "ExtraTripId", "DeadRunId", "LayoverId", "DirectionId", "StartTime", "StartDate", "ScheduleRelationship", });
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(3);
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor,
        new java.lang.String[] { "Id", "BlockId", "DriverId", "ShiftId", "Label", "LicensePlate", });
    internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(4);
    internal_static_transit_realtime_FeedMessage_TripUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor,
        new java.lang.String[] { "Trip", "Vehicle", "StopTimeUpdate", "Timestamp", "Delay", });
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor =
      internal_static_transit_realtime_FeedMessage_TripUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor,
        new java.lang.String[] { "StopSequence", "StopId", "Arrival", "Departure", "ScheduleRelationship", });
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor =
      internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor,
        new java.lang.String[] { "Delay", "Time", "Uncertainty", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(5);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor,
        new java.lang.String[] { "OperationPlanId", "AgencyId", "Trip", "Vehicle", "Position", "PassengerCounting", "EcoDriving", "CurrentStopSequence", "StopId", "CurrentStatus", "Timestamp", "CongestionLevel", "OccupancyStatus", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor =
      internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Bearing", "Odometer", "Speed", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_PassengerCounting_descriptor =
      internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_PassengerCounting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_PassengerCounting_descriptor,
        new java.lang.String[] { "ClassId", "Incoming", "Outgoing", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_descriptor =
      internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_descriptor,
        new java.lang.String[] { "Distance", "Consumption", "AverageSpeed", "AverageAcceleration", "SuddenAccelerations", "AverageDeceleration", "SuddenDecelerations", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_Consumption_descriptor =
      internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_Consumption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_EcoDriving_Consumption_descriptor,
        new java.lang.String[] { "Type", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
