// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Incidents.proto

package com.pq.gtfs.models.Incidents;

public interface FeedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.FeedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .transit_realtime.FeedMessage.FeedHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>required .transit_realtime.FeedMessage.FeedHeader header = 1;</code>
   * @return The header.
   */
  com.pq.gtfs.models.Incidents.FeedMessage.FeedHeader getHeader();
  /**
   * <code>required .transit_realtime.FeedMessage.FeedHeader header = 1;</code>
   */
  com.pq.gtfs.models.Incidents.FeedMessage.FeedHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *Nivel 1
   * </pre>
   *
   * <code>required .transit_realtime.FeedMessage.FeedEntity entity = 2;</code>
   * @return Whether the entity field is set.
   */
  boolean hasEntity();
  /**
   * <pre>
   *Nivel 1
   * </pre>
   *
   * <code>required .transit_realtime.FeedMessage.FeedEntity entity = 2;</code>
   * @return The entity.
   */
  com.pq.gtfs.models.Incidents.FeedMessage.FeedEntity getEntity();
  /**
   * <pre>
   *Nivel 1
   * </pre>
   *
   * <code>required .transit_realtime.FeedMessage.FeedEntity entity = 2;</code>
   */
  com.pq.gtfs.models.Incidents.FeedMessage.FeedEntityOrBuilder getEntityOrBuilder();
}
