// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Incidents.proto

package com.pq.gtfs.models.Incidents;

public final class Incidents {
  private Incidents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_StopTimeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Line_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Line_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Route_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Route_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_TripDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehicleDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_Stop_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_Stop_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Incidents.proto\022\020transit_realtime\032\037goo" +
      "gle/protobuf/timestamp.proto\"\303&\n\013FeedMes" +
      "sage\0228\n\006header\030\001 \002(\0132(.transit_realtime." +
      "FeedMessage.FeedHeader\0228\n\006entity\030\002 \002(\0132(" +
      ".transit_realtime.FeedMessage.FeedEntity" +
      "\032\357\001\n\nFeedHeader\022\035\n\025gtfs_realtime_version" +
      "\030\001 \002(\t\022]\n\016incrementality\030\002 \001(\01627.transit" +
      "_realtime.FeedMessage.FeedHeader.Increme" +
      "ntality:\014FULL_DATASET\022-\n\ttimestamp\030\003 \001(\013" +
      "2\032.google.protobuf.Timestamp\"4\n\016Incremen" +
      "tality\022\020\n\014FULL_DATASET\020\000\022\020\n\014DIFFERENTIAL" +
      "\020\001\032\251\026\n\nFeedEntity\022\n\n\002id\030\001 \002(\t\022\031\n\nis_dele" +
      "ted\030\002 \001(\010:\005false\022H\n\013trip_update\030\003 \001(\01323." +
      "transit_realtime.FeedMessage.FeedEntity." +
      "TripUpdate\022>\n\007vehicle\030\004 \001(\0132-.transit_re" +
      "altime.FeedMessage.VehiclePosition\022=\n\005al" +
      "ert\030\005 \001(\0132..transit_realtime.FeedMessage" +
      ".FeedEntity.Alert\032\261\006\n\nTripUpdate\022:\n\004trip" +
      "\030\001 \002(\0132,.transit_realtime.FeedMessage.Tr" +
      "ipDescriptor\022@\n\007vehicle\030\002 \001(\0132/.transit_" +
      "realtime.FeedMessage.VehicleDescriptor\022\\" +
      "\n\020stop_time_update\030\003 \002(\0132B.transit_realt" +
      "ime.FeedMessage.FeedEntity.TripUpdate.St" +
      "opTimeUpdate\022-\n\ttimestamp\030\004 \001(\0132\032.google" +
      ".protobuf.Timestamp\022\r\n\005delay\030\005 \001(\005\032\210\004\n\016S" +
      "topTimeUpdate\022\025\n\rstop_sequence\030\001 \001(\r\022\017\n\007" +
      "stop_id\030\002 \001(\t\022a\n\007arrival\030\003 \001(\0132P.transit" +
      "_realtime.FeedMessage.FeedEntity.TripUpd" +
      "ate.StopTimeUpdate.StopTimeEvent\022c\n\tdepa" +
      "rture\030\004 \001(\0132P.transit_realtime.FeedMessa" +
      "ge.FeedEntity.TripUpdate.StopTimeUpdate." +
      "StopTimeEvent\022\201\001\n\025schedule_relationship\030" +
      "\005 \001(\0162W.transit_realtime.FeedMessage.Fee" +
      "dEntity.TripUpdate.StopTimeUpdate.Schedu" +
      "leRelationship:\tSCHEDULED\032A\n\rStopTimeEve" +
      "nt\022\r\n\005delay\030\001 \001(\005\022\014\n\004time\030\002 \001(\003\022\023\n\013uncer" +
      "tainty\030\003 \001(\005\"?\n\024ScheduleRelationship\022\r\n\t" +
      "SCHEDULED\020\000\022\013\n\007SKIPPED\020\001\022\013\n\007NO_DATA\020\002\032\366\r" +
      "\n\005Alert\022\031\n\021operation_plan_id\030\001 \001(\t\022O\n\rac" +
      "tive_period\030\002 \001(\01328.transit_realtime.Fee" +
      "dMessage.FeedEntity.Alert.TimeRange\022V\n\017i" +
      "nformed_entity\030\003 \001(\0132=.transit_realtime." +
      "FeedMessage.FeedEntity.Alert.EntitySelec" +
      "tor\022R\n\005cause\030\005 \001(\01624.transit_realtime.Fe" +
      "edMessage.FeedEntity.Alert.Cause:\rUNKNOW" +
      "N_CAUSE\022U\n\006effect\030\006 \001(\01625.transit_realti" +
      "me.FeedMessage.FeedEntity.Alert.Effect:\016" +
      "UNKNOWN_EFFECT\022L\n\003url\030\007 \001(\0132?.transit_re" +
      "altime.FeedMessage.FeedEntity.Alert.Tran" +
      "slatedString\022T\n\013header_text\030\010 \001(\0132?.tran" +
      "sit_realtime.FeedMessage.FeedEntity.Aler" +
      "t.TranslatedString\022Y\n\020description_text\030\t" +
      " \001(\0132?.transit_realtime.FeedMessage.Feed" +
      "Entity.Alert.TranslatedString\032_\n\tTimeRan" +
      "ge\022)\n\005start\030\001 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\'\n\003end\030\002 \001(\0132\032.google.protobuf.Tim" +
      "estamp\032\344\003\n\016EntitySelector\022\021\n\tagency_id\030\001" +
      " \002(\t\022S\n\007line_id\030\002 \001(\0132B.transit_realtime" +
      ".FeedMessage.FeedEntity.Alert.EntitySele" +
      "ctor.Line\022\020\n\010route_id\030\003 \001(\t\022\022\n\nroute_typ" +
      "e\030\004 \001(\005\022:\n\004trip\030\005 \001(\0132,.transit_realtime" +
      ".FeedMessage.TripDescriptor\022@\n\007vehicle\030\006" +
      " \001(\0132/.transit_realtime.FeedMessage.Vehi" +
      "cleDescriptor\022\017\n\007stop_id\030\007 \001(\t\0327\n\004Line\022\027" +
      "\n\017line_short_name\030\001 \001(\t\022\026\n\016line_long_nam" +
      "e\030\002 \001(\t\032|\n\005Route\022\030\n\020route_short_name\030\001 \001" +
      "(\t\022\027\n\017route_long_name\030\002 \001(\t\022\017\n\007line_id\030\003" +
      " \001(\t\022\027\n\017line_short_name\030\004 \001(\t\022\026\n\016line_lo" +
      "ng_name\030\005 \001(\t\032\243\001\n\020TranslatedString\022`\n\013tr" +
      "anslation\030\001 \002(\0132K.transit_realtime.FeedM" +
      "essage.FeedEntity.Alert.TranslatedString" +
      ".Translation\032-\n\013Translation\022\014\n\004text\030\001 \002(" +
      "\t\022\020\n\010language\030\002 \001(\t\"\330\001\n\005Cause\022\021\n\rUNKNOWN" +
      "_CAUSE\020\001\022\017\n\013OTHER_CAUSE\020\002\022\025\n\021TECHNICAL_P" +
      "ROBLEM\020\003\022\n\n\006STRIKE\020\004\022\021\n\rDEMONSTRATION\020\005\022" +
      "\014\n\010ACCIDENT\020\006\022\013\n\007HOLIDAY\020\007\022\013\n\007WEATHER\020\010\022" +
      "\017\n\013MAINTENANCE\020\t\022\020\n\014CONSTRUCTION\020\n\022\023\n\017PO" +
      "LICE_ACTIVITY\020\013\022\025\n\021MEDICAL_EMERGENCY\020\014\"\265" +
      "\001\n\006Effect\022\016\n\nNO_SERVICE\020\001\022\023\n\017REDUCED_SER" +
      "VICE\020\002\022\026\n\022SIGNIFICANT_DELAYS\020\003\022\n\n\006DETOUR" +
      "\020\004\022\026\n\022ADDITIONAL_SERVICE\020\005\022\024\n\020MODIFIED_S" +
      "ERVICE\020\006\022\020\n\014OTHER_EFFECT\020\007\022\022\n\016UNKNOWN_EF" +
      "FECT\020\010\022\016\n\nSTOP_MOVED\020\t\032\362\003\n\016TripDescripto" +
      "r\022\017\n\007trip_id\030\001 \001(\t\022\027\n\017trip_short_name\030\002 " +
      "\001(\t\022\020\n\010route_id\030\003 \001(\t\022\030\n\020route_short_nam" +
      "e\030\004 \001(\t\022\027\n\017route_long_name\030\005 \001(\t\022\017\n\007line" +
      "_id\030\006 \001(\t\022\027\n\017line_short_name\030\007 \001(\t\022\026\n\016li" +
      "ne_long_name\030\010 \001(\t\022\025\n\rextra_trip_id\030\t \001(" +
      "\t\022\023\n\013dead_run_id\030\n \001(\t\022\022\n\nlayover_id\030\013 \001" +
      "(\t\022\024\n\014direction_id\030\014 \001(\r\022\022\n\nstart_time\030\r" +
      " \001(\t\022\022\n\nstart_date\030\016 \001(\t\022`\n\025schedule_rel" +
      "ationship\030\017 \001(\0162A.transit_realtime.FeedM" +
      "essage.TripDescriptor.ScheduleRelationsh" +
      "ip\"O\n\024ScheduleRelationship\022\r\n\tSCHEDULED\020" +
      "\000\022\t\n\005ADDED\020\001\022\017\n\013UNSCHEDULED\020\002\022\014\n\010CANCELE" +
      "D\020\003\032|\n\021VehicleDescriptor\022\n\n\002id\030\001 \001(\t\022\020\n\010" +
      "block_id\030\002 \001(\t\022\021\n\tdriver_id\030\003 \001(\t\022\020\n\010shi" +
      "ft_id\030\004 \001(\t\022\r\n\005label\030\005 \001(\t\022\025\n\rlicense_pl" +
      "ate\030\006 \001(\t\032\031\n\004Stop\022\021\n\tstop_name\030\001 \002(\t\032\223\010\n" +
      "\017VehiclePosition\022:\n\004trip\030\001 \001(\0132,.transit" +
      "_realtime.FeedMessage.TripDescriptor\022@\n\007" +
      "vehicle\030\002 \001(\0132/.transit_realtime.FeedMes" +
      "sage.VehicleDescriptor\022H\n\010position\030\003 \001(\013" +
      "26.transit_realtime.FeedMessage.VehicleP" +
      "osition.Position\022\035\n\025current_stop_sequenc" +
      "e\030\004 \001(\r\022\017\n\007stop_id\030\005 \001(\t\022f\n\016current_stat" +
      "us\030\006 \001(\0162?.transit_realtime.FeedMessage." +
      "VehiclePosition.VehicleStopStatus:\rIN_TR" +
      "ANSIT_TO\022\021\n\ttimestamp\030\007 \001(\004\022W\n\020congestio" +
      "n_level\030\010 \001(\0162=.transit_realtime.FeedMes" +
      "sage.VehiclePosition.CongestionLevel\022W\n\020" +
      "occupancy_status\030\t \001(\0162=.transit_realtim" +
      "e.FeedMessage.VehiclePosition.OccupancyS" +
      "tatus\032a\n\010Position\022\020\n\010latitude\030\001 \002(\001\022\021\n\tl" +
      "ongitude\030\002 \002(\001\022\017\n\007bearing\030\003 \001(\001\022\020\n\010odome" +
      "ter\030\004 \001(\001\022\r\n\005speed\030\005 \001(\001\"G\n\021VehicleStopS" +
      "tatus\022\017\n\013INCOMING_AT\020\000\022\016\n\nSTOPPED_AT\020\001\022\021" +
      "\n\rIN_TRANSIT_TO\020\002\"}\n\017CongestionLevel\022\034\n\030" +
      "UNKNOWN_CONGESTION_LEVEL\020\000\022\024\n\020RUNNING_SM" +
      "OOTHLY\020\001\022\017\n\013STOP_AND_GO\020\002\022\016\n\nCONGESTION\020" +
      "\003\022\025\n\021SEVERE_CONGESTION\020\004\"\257\001\n\017OccupancySt" +
      "atus\022\t\n\005EMPTY\020\000\022\030\n\024MANY_SEATS_AVAILABLE\020" +
      "\001\022\027\n\023FEW_SEATS_AVAILABLE\020\002\022\026\n\022STANDING_R" +
      "OOM_ONLY\020\003\022\036\n\032CRUSHED_STANDING_ROOM_ONLY" +
      "\020\004\022\010\n\004FULL\020\005\022\034\n\030NOT_ACCEPTING_PASSENGERS" +
      "\020\006B \n\034com.pq.gtfs.models.IncidentsP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_transit_realtime_FeedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_FeedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_descriptor,
        new java.lang.String[] { "Header", "Entity", });
    internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedHeader_descriptor,
        new java.lang.String[] { "GtfsRealtimeVersion", "Incrementality", "Timestamp", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor,
        new java.lang.String[] { "Id", "IsDeleted", "TripUpdate", "Vehicle", "Alert", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_descriptor,
        new java.lang.String[] { "Trip", "Vehicle", "StopTimeUpdate", "Timestamp", "Delay", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_descriptor,
        new java.lang.String[] { "StopSequence", "StopId", "Arrival", "Departure", "ScheduleRelationship", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_StopTimeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_TripUpdate_StopTimeUpdate_StopTimeEvent_descriptor,
        new java.lang.String[] { "Delay", "Time", "Uncertainty", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor,
        new java.lang.String[] { "OperationPlanId", "ActivePeriod", "InformedEntity", "Cause", "Effect", "Url", "HeaderText", "DescriptionText", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TimeRange_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor,
        new java.lang.String[] { "AgencyId", "LineId", "RouteId", "RouteType", "Trip", "Vehicle", "StopId", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Line_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Line_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Line_descriptor,
        new java.lang.String[] { "LineShortName", "LineLongName", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Route_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_EntitySelector_Route_descriptor,
        new java.lang.String[] { "RouteShortName", "RouteLongName", "LineId", "LineShortName", "LineLongName", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor,
        new java.lang.String[] { "Translation", });
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor =
      internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_FeedEntity_Alert_TranslatedString_Translation_descriptor,
        new java.lang.String[] { "Text", "Language", });
    internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_FeedMessage_TripDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_TripDescriptor_descriptor,
        new java.lang.String[] { "TripId", "TripShortName", "RouteId", "RouteShortName", "RouteLongName", "LineId", "LineShortName", "LineLongName", "ExtraTripId", "DeadRunId", "LayoverId", "DirectionId", "StartTime", "StartDate", "ScheduleRelationship", });
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(3);
    internal_static_transit_realtime_FeedMessage_VehicleDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehicleDescriptor_descriptor,
        new java.lang.String[] { "Id", "BlockId", "DriverId", "ShiftId", "Label", "LicensePlate", });
    internal_static_transit_realtime_FeedMessage_Stop_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(4);
    internal_static_transit_realtime_FeedMessage_Stop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_Stop_descriptor,
        new java.lang.String[] { "StopName", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor =
      internal_static_transit_realtime_FeedMessage_descriptor.getNestedTypes().get(5);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor,
        new java.lang.String[] { "Trip", "Vehicle", "Position", "CurrentStopSequence", "StopId", "CurrentStatus", "Timestamp", "CongestionLevel", "OccupancyStatus", });
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor =
      internal_static_transit_realtime_FeedMessage_VehiclePosition_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_VehiclePosition_Position_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Bearing", "Odometer", "Speed", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
